### ISSUE TITLE
Support for Gitlab 6.4.3

### ISSUE THREAD

**Issue by isodude** [caseyscarborough/gitlab-install#2]
Hi, is it possible to get support for 6.4.3, as it's the latest stable?

https://gitlab.com/gitlab-org/gitlab-ce/commit/42131d0189bbc0e88be72e6a76405140cbd79fc8

Cheers,
Josef

**Comment by caseyscarborough** [comment]
Sorry for the late reply. I'll try to make support for the latest version, which looks like it's up to 6.6 now. I'd be more than willing to accept a pull request for this also.

**Comment by isodude** [comment]
Made a lot of changes in my fork, haven't tested it lately but I think it
works, have a look at ut maybe? Just for ubuntu though

**Comment by caseyscarborough** [comment]
Okay, great. I'll check that out. I think Ubuntu is probably what most people are going to want to use this with, so I'm probably going to try to focus on that for now.

**Comment by isodude** [comment]
Should be fairly easy to just make the script platform agnostic, that's
what's I'm aiming for.

I noticed small problems like that redis didnt catch the locale timezone
and became out of sync,

also that unicorn needed a little more timeout than 30s to compile the
first time around ;-)

**Comment by isodude** [comment]
But to be honest I ran out of time, and it's true that most use ubuntu
anyway :-)
